- Finished most castlwars issues (WIP)
RSPSApp/elvarg-rsps pull request #167
Opened 2023-01-06 21:16 UTC by DrHenny

- Added catapult state
- Debug command for redX interface ::cwar x y
- Added useitemonobject actions for castlewars
- Added search for spawned object / map object by id/location
- Added better way to send graphics to location players at position
- Added everything from this issues tab https://github.com/RSPSApp/elvarg-rsps/issues/140

2023-01-06 23:38 UTC, tobywisener commented on ElvargServer/src/main/java/com/elvarg/net/packet/impl/UseItemPacketListener.java
> +            return;
Does this need to be inside the WallToTask completion callback?

2023-01-06 23:38 UTC, tobywisener commented on ElvargServer/src/main/java/com/elvarg/game/content/minigames/impl/CastleWars.java
> +                        World.sendLocalGraphics(305, destination);
Does the catapult always kill everyone instantly within a 3 tile distance? I thought the damage varied

2023-01-07 01:23 UTC, DrHenny commented on ElvargServer/src/main/java/com/elvarg/game/content/minigames/impl/CastleWars.java
> +                        World.sendLocalGraphics(305, destination);
We don't have the damage or distance calculations, I don't see them on wiki. It's a placeholder until we get the information <3

2023-01-07 01:24 UTC, DrHenny commented on ElvargServer/src/main/java/com/elvarg/net/packet/impl/UseItemPacketListener.java
> +            return;
We don't have a walkToTask callback anymore, we now use a different system and this is called upon pathing tot he destination it will run the runnable

2023-01-07 01:35 UTC, DrHenny commented on ElvargServer/src/main/java/com/elvarg/net/packet/impl/UseItemPacketListener.java
> +            return;
Ahh, my bad I didn't realize it was outside of the execution for on arrival.

2023-01-07 07:20 UTC, tobywisener commented on ElvargServer/src/main/java/com/elvarg/net/packet/impl/UseItemPacketListener.java
> +            return;
Easy done lol I do it all the time 😂

2023-01-07 07:20 UTC, tobywisener commented on ElvargServer/src/main/java/com/elvarg/game/content/minigames/impl/CastleWars.java
> +                        World.sendLocalGraphics(305, destination);
Okay man all good 😸

2023-01-07 07:22 UTC, tobywisener approved these changes
Great stuff, another awesome contribution. We're the only 317 base to have catapult!!!!

2023-01-09 17:45 UTC, tobywisener requested changes
Noticed a few crashes and misc issues, going to fix them and update PR with the fix for them and for the red x

- [ ] Crash when opening interface sometimes when players catapult attributes weren't set
- [ ] Players can move their x and y coord for catapult way over 30
- [ ] Need to test if broken catapult updates game interface
- [ ] Need to change damage of catapult to be less deadly. Until mod ash replies [here](https://twitter.com/tobywisener/status/1612516122573537281) we can just use a basic formula of distance, max hit 50

2023-01-10 18:00 UTC, closed without merging