Pestcontrol latest
RSPSApp/elvarg-rsps pull request #207
Opened 2023-02-17 07:34 UTC by DrHenny

Lists from commits are below with what was changed. Was told to make a PR with latest progress

2023-03-01 15:50 UTC, tobywisener requested changes
Overall great job, some things needing changed and some questions

2023-03-01 15:50 UTC, tobywisener commented on ElvargServer/data/definitions/shops.json
> +    "name": "Void Knight Magic Store",
Nice, probably want to make a ShopCurrency impl for this

Can use
```com/elvarg/game/model/container/shop/currency/impl/PointsCurrency.java```

as a reference

2023-03-01 15:50 UTC, tobywisener commented on ElvargServer/src/main/java/com/elvarg/game/collision/RegionManager.java
> +
Delete empty switch please

2023-03-01 15:50 UTC, tobywisener commented on ElvargServer/src/main/java/com/elvarg/game/content/combat/CombatFactory.java
> +        if (attacker.useProjectileClipping() && !RegionManager.canProjectileAttack(attacker, target) && !overrideEntity(target)) {
I think you can delete overrideEntity now since my .patch had the fix for this (if player is using melee don't check for projectile blocks)

2023-03-01 15:50 UTC, tobywisener commented on ElvargServer/src/main/java/com/elvarg/game/content/combat/method/CombatMethod.java
> +    public void onTick(NPC npc, Mobile target) {
Can we add a comment to the top of this function? The comment could explain exactly when onTick is.. I'm not sure just by reading this, is it on every attack tick? is it every server/game tick?

2023-03-01 15:50 UTC, tobywisener commented on ElvargServer/src/main/java/com/elvarg/game/content/minigames/impl/pestcontrol/PestControl.java
> +        Task noviceLobbyTask = new Task(1, PestControlBoat.NOVICE.name()) {
These tasks just run forever, can't we do it on postEnter on the areas instead and use CountdownTask?

2023-03-01 15:50 UTC, tobywisener commented on ElvargServer/src/main/java/com/elvarg/game/content/minigames/impl/pestcontrol/PestControl.java
> +        /**
Don't need this code anymore? Remove pls

2023-03-01 15:50 UTC, tobywisener commented on ElvargServer/src/main/java/com/elvarg/game/content/minigames/impl/pestcontrol/PestControl.java
> +        for (NPC npc : spawned_npcs) {
We should store a reference to the knight NPC like we do in CastleWars with Lanthas. 

Make `spawnNPC` return the NPC instance, then set it to a static variable inside `setupEntities`. We can store one void knight reference per instance when we do instancing. Looping every NPC every tick is unnecessary will be very inefficient compared to O(1) with the static reference. Its actually called multiple times per tick potentially so this is pretty important to fix.

2023-03-01 15:50 UTC, tobywisener commented on ElvargServer/src/main/java/com/elvarg/game/entity/impl/player/Player.java
> +	public int pcPoints;
Are we not tracking pcDamage anymore / is it an attr now?

2023-03-01 15:50 UTC, tobywisener commented on ElvargServer/src/main/java/com/elvarg/game/task/impl/CombatPoisonEffect.java
> +
Can we remove all these extra lines pls

2023-03-01 15:52 UTC, tobywisener commented on ElvargServer/src/main/java/com/elvarg/game/entity/impl/player/Player.java
> +	public int pcPoints;
Nvm its an attr just seen. nice one

2023-03-02 04:14 UTC, DrHenny commented on ElvargServer/src/main/java/com/elvarg/game/content/minigames/impl/pestcontrol/PestControl.java
> +        /**
We do.

2023-03-02 14:00 UTC, DrHenny commented on ElvargServer/src/main/java/com/elvarg/game/content/combat/method/CombatMethod.java
> +    public void onTick(NPC npc, Mobile target) {
added docuementation to the method.

2023-03-02 14:01 UTC, DrHenny commented on ElvargServer/data/definitions/shops.json
> +    "name": "Void Knight Magic Store",
It's for magic runes which use GP. You only call points currency when it's a different type of currency. So as for this, It's not needed.

2023-03-02 14:35 UTC, DrHenny commented on ElvargServer/src/main/java/com/elvarg/game/content/minigames/impl/pestcontrol/PestControl.java
> +        Task noviceLobbyTask = new Task(1, PestControlBoat.NOVICE.name()) {
done

2023-03-02 15:35 UTC, tobywisener approved these changes

2023-03-02 15:36 UTC, merged